# TensorFlow Fold Quick Start

TensorFlow Fold is a library for turning complicated Python data structures into TensorFlow Tensors.

In [2]:
# boilerplate
import random
import tensorflow as tf
sess = tf.InteractiveSession()
import tensorflow_fold as td

The basic elements of Fold are *blocks*. We'll start with some blocks that work on simple data types.

In [3]:
scalar_block = td.Scalar()
vector3_block = td.Vector(3)

Blocks are functions with associated input and output types.

In [4]:
def block_info(block):
    print("%s: %s -> %s" % (block, block.input_type, block.output_type))
    
block_info(scalar_block)
block_info(vector3_block)

<td.Scalar dtype='float32'>: PyObjectType() -> TensorType((), 'float32')
<td.Vector dtype='float32' size=3>: PyObjectType() -> TensorType((3,), 'float32')


We can use `eval()` to see what a block does with its input:

In [5]:
scalar_block.eval(42)

array(42.0, dtype=float32)

In [6]:
vector3_block.eval([1,2,3])

array([ 1.,  2.,  3.], dtype=float32)

Not very exciting. We can compose simple blocks together with `Record`, like so:

In [7]:
record_block = td.Record({'foo': scalar_block, 'bar': vector3_block})
block_info(record_block)

<td.Record ordered=False>: PyObjectType() -> TupleType(TensorType((3,), 'float32'), TensorType((), 'float32'))


We can see that Fold's type system is a bit richer than vanilla TF; we have tuple types! Running a record block does what you'd expect:

In [8]:
record_block.eval({'foo': 1, 'bar': [5, 7, 9]})

(array([ 5.,  7.,  9.], dtype=float32), array(1.0, dtype=float32))

One useful thing you can do with blocks is wire them up to create pipelines using the `>>` operator, which performs function composition. For example, we can take our two tuple tensors and compose it with `Concat`, like so:

In [9]:
record2vec_block = record_block >> td.Concat()
record2vec_block.eval({'foo': 1, 'bar': [5, 7, 9]})

array([ 5.,  7.,  9.,  1.], dtype=float32)

Note that because Python dicts are unordered, Fold always sorts the outputs of a record block by dictionary key. If you want to preserve order you can construct a Record block from an OrderedDict.

The whole point of Fold is to get your data into TensorFlow; the `Function` block lets you convert a TITO (Tensors In, Tensors Out) function to a block:

In [10]:
negative_block = record2vec_block >> td.Function(tf.negative)
negative_block.eval({'foo': 1, 'bar': [5, 7, 9]})

array([-5., -7., -9., -1.], dtype=float32)

This is all very cute, but where's the beef? Things start to get interesting when our inputs contain sequences of indeterminate length. The `Map` block comes in handy here:

In [11]:
map_scalars_block = td.Map(td.Scalar())

There's no TF type for sequences of indeterminate length, but Fold has one:

In [12]:
block_info(map_scalars_block)

<td.Map element_block=<td.Scalar dtype='float32'>>: None -> SequenceType(TensorType((), 'float32'))


Right, but you've done the TF [RNN Tutorial](https://www.tensorflow.org/tutorials/recurrent/) and even poked at [seq-to-seq](https://www.tensorflow.org/tutorials/seq2seq/). You're a wizard with [dynamic rnns](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn). What does Fold offer?

Well, how about jagged arrays?

In [13]:
jagged_block = td.Map(td.Map(td.Scalar()))
block_info(jagged_block)

<td.Map element_block=<td.Map element_block=<td.Scalar dtype='float32'>>>: None -> SequenceType(SequenceType(TensorType((), 'float32')))


The Fold type system is fully compositional; any block you can create can be composed with `Map` to create a sequence, or `Record` to create a tuple, or both to create sequences of tuples or tuples of sequences:

In [14]:
seq_of_tuples_block = td.Map(td.Record({'foo': td.Scalar(), 'bar': td.Scalar()}))
seq_of_tuples_block.eval([{'foo': 1, 'bar': 2}, {'foo': 3, 'bar': 4}])

[(array(2.0, dtype=float32), array(1.0, dtype=float32)),
 (array(4.0, dtype=float32), array(3.0, dtype=float32))]

In [15]:
tuple_of_seqs_block = td.Record({'foo': td.Map(td.Scalar()), 'bar': td.Map(td.Scalar())})
tuple_of_seqs_block.eval({'foo': range(3), 'bar': range(7)})

([array(0.0, dtype=float32),
  array(1.0, dtype=float32),
  array(2.0, dtype=float32),
  array(3.0, dtype=float32),
  array(4.0, dtype=float32),
  array(5.0, dtype=float32),
  array(6.0, dtype=float32)],
 [array(0.0, dtype=float32),
  array(1.0, dtype=float32),
  array(2.0, dtype=float32)])

Most of the time, you'll eventually want to get one or more tensors out of your sequence, for wiring up to your particular learning task. Fold has a bunch of built-in reduction functions for this that do more or less what you'd expect:

In [16]:
((td.Map(td.Scalar()) >> td.Sum()).eval(range(10)),
 (td.Map(td.Scalar()) >> td.Min()).eval(range(10)),
 (td.Map(td.Scalar()) >> td.Max()).eval(range(10)))
        

(array(45.0, dtype=float32),
 array(0.0, dtype=float32),
 array(9.0, dtype=float32))

The general form of such functions is `Reduce`:

In [17]:
(td.Map(td.Scalar()) >> td.Reduce(td.Function(tf.multiply))).eval(range(1,10))

array(362880.0, dtype=float32)

If the order of operations is important, you should use `Fold` instead of `Reduce` (but if you can use `Reduce` you should, because it will be faster):

In [18]:
((td.Map(td.Scalar()) >> td.Fold(td.Function(tf.divide), tf.ones([]))).eval(range(1,5)),
 (td.Map(td.Scalar()) >> td.Reduce(td.Function(tf.divide), tf.ones([]))).eval(range(1,5)))  # bad, not associative!

(array(0.0416666679084301, dtype=float32),
 array(0.6666666865348816, dtype=float32))

Now, let's do some learning! This is the part where "magic" happens; if you want a deeper understanding of what's happening here you might want to jump right to our more formal [blocks tutorial](https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/blocks.md) or learn more about [running blocks in TensorFlow](https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/running.md)

In [36]:
def reduce_net_block():
    net_block = td.Concat() >> td.FC(2000) >> td.FC(200) >> td.FC(1, activation=None) >> td.Function(lambda xs: tf.squeeze(xs, axis=1))
    return td.Map(td.Scalar()) >> td.Reduce(net_block)


The `reduce_net_block` function creates a block (`net_block`) that contains a two-layer fully connected (FC) network that takes a pair of scalar tensors as input and produces a scalar tensor as output. This network gets applied in a binary tree to reduce a sequence of scalar tensors to a single scalar tensor.

One thing to notice here is that we are calling [`tf.squeeze`](https://www.tensorflow.org/versions/r1.0/api_docs/python/array_ops/shapes_and_shaping#squeeze) with `axis=1`, even though the Fold output type of `td.FC(1, activation=None)` (and hence the input type of the enclosing `Function` block) is a `TensorType` with shape `(1)`. This is because all Fold blocks actually run on TF tensors with an implicit leading batch dimension, which enables execution via [*dynamic batching*](https://arxiv.org/abs/1702.02181). It is important to bear this in mind when creating `Function` blocks that wrap functions that are not applied elementwise.

In [20]:
def random_example(fn):
    length = random.randrange(1, 30)
    data = [random.uniform(0,1) for _ in range(length)]
    result = fn(data)
    return data, result

The `random_example` function generates training data consisting of `(example, fn(example))` pairs, where `example` is a random list of numbers, e.g.:

In [21]:
random_example(sum)

([0.36042501825802875,
  0.5465363034978248,
  0.4596324571390036,
  0.7510162230689412,
  0.46724518380791735,
  0.22865208932697,
  0.3702777514159542,
  0.742719683191877],
 3.9265047097065167)

In [107]:
random_example(min)
cell = td.ScopedLayer(tf.contrib.rnn.BasicLSTMCell(num_units=16), 'char_cell')
blk = td.Map(td.Scalar() >> td.Function(lambda x: tf.reshape(x, [-1,1]))) >> td.RNN(cell) >> td.GetItem(1) >> td.GetItem(1) >> td.FC(1)#>> td.Function(lambda xs: tf.squeeze(xs, axis=1))

In [108]:
def train(fn, batch_size=100):
    net_block = blk #reduce_net_block()
    compiler = td.Compiler.create((net_block, td.Scalar()))
    y, y_ = compiler.output_tensors
    loss = tf.nn.l2_loss(y - y_)
    train = tf.train.AdamOptimizer().minimize(loss)
    sess.run(tf.global_variables_initializer())
    validation_fd = compiler.build_feed_dict(random_example(fn) for _ in range(1000))
    for i in range(2000):
        sess.run(train, compiler.build_feed_dict(random_example(fn) for _ in range(batch_size)))
        if i % 100 == 0:
            print(i, sess.run(loss, validation_fd))
    return net_block
                 

Now we're going to train a neural network to approximate a reduction function of our choosing. Calling `eval()` repeatedly is super-slow and cannot exploit batch-wise parallelism, so we create a [`Compiler`](https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/py/td.md#compiler). See our page on [running blocks in TensorFlow](https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/running.md) for more on Compilers and how to use them effectively.

In [109]:
#blk.eval([1,1,1,1,1,1])
sum_block = train(sum)

/home/moon/Envs/tf1/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:95: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


0 3.65784e+07
100 1.59493e+07
200 1.15505e+07
300 1.09198e+07
400 1.06573e+07
500 1.04791e+07
600 1.03442e+07
700 1.02375e+07
800 1.01577e+07
900 1.00852e+07
1000 1.00218e+07
1100 9.97249e+06
1200 9.92328e+06
1300 9.86766e+06
1400 9.8354e+06
1500 9.79023e+06
1600 9.75208e+06
1700 9.72531e+06
1800 9.69557e+06
1900 9.67047e+06


In [97]:
sum_block.eval([1,1])

array([ 7.61186552], dtype=float32)

Breaking news: deep neural network learns to calculate 1 + 1!!!!

Of course we've done something a little sneaky here by constructing a model that can only represent associative functions and then training it to compute an associative function. The technical term for being sneaky in machine learning is [inductive bias](https://en.wikipedia.org/wiki/Inductive_bias).

In [33]:
min_block = train(min)

/home/moon/Envs/tf1/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:91: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


0 881.552
100 10.4458
200 8.65752
300 5.636
400 2.79715
500 0.860903
600 0.357025
700 0.247206
800 0.18569
900 0.148382
1000 0.123437
1100 0.100547
1200 0.0806426
1300 0.0673405
1400 0.0556801
1500 0.0485146
1600 0.0428071
1700 0.0377028
1800 0.0316301
1900 0.0282389


In [45]:
min_block.eval([6, 3, 4])

array(2.91923451423645, dtype=float32)

Oh noes! What went wrong? Note that we trained our network to compute `min` on positive numbers; negative numbers are outside of its input distribution.

In [41]:
min_block.eval([0.3, 0.2, 0.9])

array(0.20059311389923096, dtype=float32)

Well, that's better. What happens if you train the network on negative numbers as well as on positives? What if you only train on short lists and then evaluate the net on long ones? What if you used a `Fold` block instead of a `Reduce`? ...  Happy Folding!